# fly.toml app configuration file generated for medical-rag-solitary-silence-8893 on 2025-04-10T20:26:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rag-lvmqca"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
